### ISSUE TITLE
Collab?

### ISSUE THREAD

**Issue by amcdnl** [WealthBar/a2d3#2]
Would you be interesting in collaborating on this project with us? https://github.com/swimlane/ng2d3

**Comment by chrisnicola** [comment]
Possibly what kind of collaboration were you thinking?

**Comment by amcdnl** [comment]
Just worked together on a unified library :)

**Comment by chrisnicola** [comment]
We are already using A2D3 in projects that are being released imminently. It is functionally equivalent to our original AngularD3 project, which is what we have been using for some time now  with Angular 1.x. So we are essentially ready to go for our Angular 1.x->2.x upgrade plan. Because of this I don't think it would be practical for our team to switch over to your project at this point, assuming that that is what you were asking.

I'm happy to wait and see how things develop. Alternatively, if you see enough value in what we are doing here I would always welcome any contributions or suggestions.

**Comment by amcdnl** [comment]
I wan'st nesc suggesting a switch over, more like a collaboration on making a community project where we could eventually use the same one.
